### ISSUE TITLE
Bug: Form allows submit without date

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia-management#17]
In case of entering destroyed nest, the form in the new-app currently allows true for destroyed nest without entering a date. 

**Steps to reproduce:**
- fill the form
- add true in destroyed field
- don't fill date, submit form
- check entry submitted 

**Actual behaviour:**
- destroyed date field empty

**Required behaviour:** 

- form produces error message when date not entered

**Comment by manandearth** [comment]
creating new js form to replace the Clojure one

**Comment by manandearth** [comment]
new form done 
https://github.com/manandearth/hirundia/pull/29
