### ISSUE TITLE
Colours represented on map

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia-management#18]
Colours of birds represented on the map should correspond to the chart of colours indicating birds under the map, using the colours below:

Golondrina comun - ![#cc0000](https://placehold.it/15/cc0000/000000?text=+) `#cc0000`
Golondrina daurica - ![#cc6666](https://placehold.it/15/cc6666/000000?text=+) `#cc6666`
Vencejo comun - ![#3300ff](https://placehold.it/15/3300ff/000000?text=+) `#3300ff`
Vencejo palido - ![#669999](https://placehold.it/15/669999/000000?text=+) `#669999`
Avion comun - ![#ffcc33](https://placehold.it/15/ffcc33/000000?text=+) `#ffcc33`

**Comment by manandearth** [comment]
resolved in https://github.com/manandearth/hirundia/pull/31
