### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by manandearth** [manandearth/hirundia-management#2]
Home/About page is guide - how to use the form.

- [x] remove swallow definition
- [ ] make the form look less like the form... ( some people might try to fill it ...) disable fields...

**Comment by stwiss** [comment]
Cernícalo primilla - Lesser kestrel - Falco naumanni
Golondrina común - Barn swallow - Hirundo rustica
Avión común - House martin - Delichon urbicum
Vencejo común - Common swift - Apus apus

**Comment by manandearth** [comment]
no about page just the home one.
