### ISSUE TITLE
Explanatory text to add above map

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia-management#30]
Add the following text above the map on the control panel page:

>  The map below shows the nests in the area defined by the map, if you zoom in or out the amount of nests will increase or decrease accordingly as the defined range changes.
>  The table below shows the amounts of nests selected within the map frame at any given time. You can scroll around, zoom out to include a wider area and the table will adjust the data displayed accordingly. 
> You can select to see displayed either the total entries, the current entries or only entries of nests that have been destroyed.   
> 

*I will of course translate this to Spanish if you think that the text in concise in describing what is displayed with the map and table.*

**Comment by manandearth** [comment]
solved with:
> La siguinte tabla es dinamica y se actualiza para representar los datos de la zona cuadrada en la ventanilla.
