### ISSUE TITLE
Formatting data on Control Panel page

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia-management#31]
#### Some changes to improve the display of data within the table underneath the map display:

- Capitalize bird species and add scientific names in brackets alongside common names. 

- Capitalize **clave** and **cantidad** as the titles of the table.

- Total Entries, Current Entries and Destroyed Entries translated into Spanish.

**Comment by manandearth** [comment]
> Capitalize bird species and add scientific names in brackets alongside common names.
what are the scientific names? can you point at that please? @stwiss

**Comment by stwiss** [comment]
In the table below the map, capitalize bird names, no need to put scientific names too.

**Comment by manandearth** [comment]
resolved in:
https://github.com/manandearth/hirundia/pull/33
