### ISSUE TITLE
Rewrite the app in JS

### ISSUE THREAD

**Issue by manandearth** [manandearth/hirundia-management#4]
The dashboard is written in ClojureScript.
Rewriting in in JS will help maintenance as well as adding features.

We want the `Leaflet` map to have more functionality and the `VegaLite` viz to also be more interactive. 

 Need to find out:
- Can I inject an app in the same page?
- Can I work interactively with the Clojure backend and a Create-React-App front? 
- what about packaging and deployment?

**Comment by manandearth** [comment]
A client folder created with `mpx create-react-app client` which is rendered into its own div element by id , simple.

**Comment by manandearth** [comment]
Leaflet also requires its own div and id.

The only thing left to check is deployment ( hopefully it will all be packed anyway...)

**Comment by stwiss** [comment]
Where do we stand on this?

**Comment by manandearth** [comment]
@stwiss , It's the bulk of the work at the moment. 
I will try to get what I have deployed by tomorrow so we could speak about concrete issues
If all goes well, you could create issue for specific tasks in the app.
The one unknown is deployment of the new React app together with the Clojure backend.
Locally it works well.

**Comment by stwiss** [comment]
Great.

**Comment by manandearth** [comment]
The deployment went smoothly, no unknowns.
