### ISSUE TITLE
Define search area

### ISSUE THREAD

**Issue by stwiss** [manandearth/hirundia-management#8]
Investigate the best way to manage projects in different localities. Limit search area ? Set up projects specific to certain areas and define area? Barbate / Conil / Benalup / Vejer ? With the ability to zoom out to an overview of all projects within the map?

**Comment by manandearth** [comment]
At this stage I will add a radius/limiting area slider or box so as to filter data by location.
The possibility to log into a place-specific db, and make the whole presentation place-specific needs to be discussed and planned.

**Comment by manandearth** [comment]
the solution was having a dynamic data table that gives the data of what is within the viewport.
zoom in and pan result in updates.
